### ISSUE TITLE
List of present individuals in group-comp file often does not seem to those marked as present in the weights file

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#100]
For example there are lots of -1 values in the present field in the group-comp file but lots of records of mongooses being present in these sessions in the weights file. 

This is not a great problem in itself as the weights file is in a more usable format (one line per individual in each group comp session). However it just makes me wonder if the same error sometimes occurs on the babysitting and pregnancy fields in the group-comp file which are not output elsewhere. There are definitely occasions when no babysitter or pregnant female is recorded on the app but is on Psion system. This may well be the guys forgetting to select an individual but it would just be good to double check.

**Comment by HarryHMarshall** [comment]
Is this actually because the present field is now defunct and has been replaced by an individual presence/absence record for each mongoose in the weights file? If so, close?

**Comment by nebogeo** [comment]
Correct, the present flag in the weight means it was there but not weighed.
