### ISSUE TITLE
"Name not found" errors

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#101]
"Name not found" is still occasionally output in field where there should be an ID. The occurrence rate is pretty low but it would be good to work out what was causing this....

**Comment by nebogeo** [comment]
There is one truly mystery unknown mongoose that had 3 occurrences very early on - the only way this could have happened is if a new mongoose was made on a tablet, then referred to (in a group-comp in this case) then for some reason it never synced with the Pi, or was ever heard of again :) We need to keep an eye on this - but it seems to be ok so far, and could have been the result of some messing about at the start.

Later on there seem to be some "???" records, which were also coming through as "Name not found". I've now fixed this in the mongose-exporter - same now for "None" too.

**Comment by HarryHMarshall** [comment]
Ah that sounds much better. I'm sure the three occurrences early on were 
a result of us and guys the guys playing around with the app early on. 
Great that the guys have been using the ??? ID. Hopefully it means the 
IDs they are entering are those with a high degree of confidence.
