### ISSUE TITLE
Oestrus and Pregnancy focal setup screen mongoose selector

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#104]
Needs to be filtered to have only females over 6 months available for selection. Currently all mongooses (or all mongooses over 6 months?) are available.

**Comment by nebogeo** [comment]
I can't replicate this but I noticed the filtering for these were working a bit differently, so now it's the same as the others, lets leave this open and check when I've done a new test release.

**Comment by HarryHMarshall** [comment]
What ever you have done it has resolved it. Still get the problem on the 1st version of 2.0 you sent through in mid0Sept but the 2nd version you sent through at the end of Sept only brings up females in the oestrus and preg focal setup screen.

I think this can be closed.
