### ISSUE TITLE
Oestrus focal: ID selection in male-male aggression screen

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#108]
Is it possible to grey out the ID selected in under ID1 in the ID2 selector and vice versa? I.e. if an ID is selected in one selector it cannot be selected in the other.

Also, is it possible for the IDs in the initiator, winner and owner menus to to change to the IDs selected under #1 and #2? (This second one may be be a bit more complicated?)

**Comment by nebogeo** [comment]
removed intitator, and changed winner and owner to receiver/intitator selection
