### ISSUE TITLE
Pregnancy focal review chanage

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#110]
Looks like these are stored in the same table as the oestrus aggression and affiliation records? I.e. They are listed in the preg focal review changes as "oestrus-focal-aggr" and oestrus-focal-affil". 

I can understand why this makes sense (they are the same behavioural interaction being recorded), however if it's easier to store these records like this they will still need to be labelled as being from oestrus or preg focals in the review changes. As it stands I'm pretty sure it's the sort of the thing that the guys will pick up on as an error and they will worry that the data is being stored in the wrong place.

**Comment by nebogeo** [comment]
Nope - that was a bug :)
