### ISSUE TITLE
GPS fixes when screen is off: no fixes when group comp is not left open

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#113]
I've done quite a bit of testing as to when the app will keep recording GPS fixes when you turn the screen off. The good news is it does, but only when you leave the group composition sequence open. 

If you start a group composition, the go out of it to start a focal, finish the focal but don't go back into the group composition sequence before turning the screen off (e.g. stay at the "Start Observation" window) then no GPS coordinates are logged in the gpslog file at all.

As long as we are aware of this it's not a big issue - just perhaps a minor snag to fix if possible at some point.

There seem to be some GPS fixes which are not associated with a focal or group composition session so presumably the app is sometimes recording GPS points when neither of these have been started?

**Comment by nebogeo** [comment]
Just a thought - are you moving around while testing this? The GPS is currently set up to update when you've moved 1 metre or every 30 seconds, so if you're stationary there will be less log entries...

**Comment by HarryHMarshall** [comment]
No, but just trying that outside with wifi turned off at the moment. 
Look a bit like I am trying to give cars in the TIC car park a ticket...

**Comment by HarryHMarshall** [comment]
Hmmm..it seems to have recorded far fewer GPS points with me moving 
around outside. I was out there between 12:00 and 12:15 running though 
various routines of starting group compositions, doing focals and and 
turning the screen off with the group comp sequence either open or shut. 
However the last GPS point in the log is from 12:01. I definitely saw 
the GPS indicator appear quite a few times, flashing briefly before 
disappearing. I'm not sure I ever saw the coordinates flash up in the 
screen, however I could have missed these looking around of at other 
bits of the screen.

Is it just having a problem getting a  GPS fix in cloudy UK with 
buildings around? (I went out into the car parks but I guess there were 
some building around at various points).

**Comment by HarryHMarshall** [comment]
Hi Dave,

Ok I am pretty sure I have worked out what is causing the GPS points to stop being logged, and it's nothing to do with the screen being turned off (!).

It seems that the following causes a problem (with notes as to whether GPS points are being collected)
1. Start a group composition, e..g collecting weights (GPS points being collected)
2. Hit the back button to go to the Start Observation screen (GPS points being collected)
3. Start a focal follow (GPS points being collected)
4. Hit exit to finish the focal follow are restart the same group composition as it point 1 ((GPS points NOT being collected)  
5. Continue group composition with mongoose data collected in point 1 still present (GPS points NOT being collected)
6. Finish group composition (GPS points NOT being collected)
   and then either:
   7a. Start a new group composition, e.g. on a different pack (GPS points NOT being collected)
   or
   7b. End the app by hitting remove all and then restart it and start a group composition (GPS points being collected again)

You can detect the stages that GPS points are not being collected by the GPS indicator blinking but then no coordinates flashing up on the screen. These periods correspond with time gaps in the gpslog file. 

I don't get this error if I don't start a focal follow, i.e. just go in and out of the group composition sequence. Similarly, this error doesn't correspond with whether or not the screen is turned off at any point. So, it seems to be that switching out of the focal follow and back into the group composition stops the GPS points being taken. Looking in the review changes all the mongoose data collected in the group comp and the focal follow is there, and the group comp data collected before the GPS points stop remains after they stop.

I guess there is a bug somewhere that this sequence of button taps exposes? It seems that once it happens the only way to fix it is to restart the app as if you start a new group comp without doing this then GPS points still aren't recorded.

Hope that all makes sense. I'll just write a more general email now. I think would still be worth releasing the app to guys for them to try out as I think we've got the stage where their feedback and full field testing would be very valuable, but just with the caveat about this issue.

Cheers, Harry

**Comment by nebogeo** [comment]
Fixed! (finally :)
