### ISSUE TITLE
Add in "submission" as a level in the aggressive behaviour event in the oestrus and preg focals

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#115]
Francis pointed out that I missed one of the types of aggressive behaviours off the mock ups I sent to you for the female oestrus and pregnancy focals.

Please could you add "submission" as an extra option to the level menu in the aggression events recorded in the oestrus and pregnancy focals?

**Comment by nebogeo** [comment]
Do you want this on all the aggression levels or just oestrus/pregnancy? I only ask as at the moment all aggression levels are the same... (soz for the delay btw)

**Comment by nebogeo** [comment]
Done what you've said (i.e. left pup aggression and oestrus male-male aggression as it was) as it seems to make sense...

**Comment by HarryHMarshall** [comment]
Hi Dave, I put your suggestion of including 'submission' in the level menu in all the aggression events (i.e. the pup aggression in the pup focal and male-male aggression in oestrus focal too and he thought it was a really good idea. So if you could add it in there too when you get a chance that would be great.

Cheers, Harry
