### ISSUE TITLE
Text size on newer tablet model 

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#116]
![img_0089](https://cloud.githubusercontent.com/assets/6039714/11609492/a4639614-9b7f-11e5-8871-255c13a2e1d8.JPG)

**Comment by HarryHMarshall** [comment]
It appears the app displays the IDs on the newer tablets (Galaxy Tab S 10.5) with very big text but doesn't do this on the older model (Galaxy Note 10.1). I thouhgt we had tested this before we took the newer models out but it got missed in pre-leaving madness.

Any ideas?

**Comment by nebogeo** [comment]
Hmm, try setting the font size in the settings for the tablet?

**Comment by HarryHMarshall** [comment]
Sorry - should have mentioned Francis is trying that (it's the one thing 
I could think of). If that's the first thing you think of too then it 
sounds hopeful...

Will let you know!
