### ISSUE TITLE
pup focal scan out of time fix

### ISSUE THREAD

**Issue by nebogeo** [fo-am/mongoose-2000#12]
stack up or pause

**Comment by HarryHMarshall** [comment]
(Duplicating email conversation). My thinking is that a scan that has not been entered after a minute should just get entered as empty and not recorded. After a minute it's unlikely to be able to be entered accurately, plus the focus should now be on accurately recording the most recent scan. I think pausing would just create more problems as there may well be a reason the scan is not entered (e.g. the observer forgot or was distracted).

**Comment by nebogeo** [comment]
Now it ignores un-entered scans, just pushes the time onward.

**Comment by HarryHMarshall** [comment]
This looks like it's working well. Just checking but my "pushes the time on" do you mean it just ignores the unentered scan from the previous minute?

**Comment by nebogeo** [comment]
yes, it only gets recorded when you press "done"
