### ISSUE TITLE
tablet on/off = pause

### ISSUE THREAD

**Issue by nebogeo** [fo-am/mongoose-2000#15]
need to highlight pause button if this is how it's supposed to work...?

**Comment by HarryHMarshall** [comment]
Would be great to be able to disable the power off button, or have some sort of window asking if you really do want to turn it off, but I'm not sure this is possible....?

At the moment, accidentally hitting the power off button causes the focal timer to pause but when you turn the tablet back on although the timer is stopped the pause button is not highlighted. I guess this either needs altering so the focal is not paused when the power off button is hit, or so it is obviously paused?

**Comment by nebogeo** [comment]
Not sure we can disable the power button - but the timer should work from the internal clock so it keeps the time even when waking again. Currently it's stopping which is incorrect.

**Comment by HarryHMarshall** [comment]
Still seems to stop if you turn the tablet on and off... Also I went into the tablet settings in the middle of a focal to try to change the sound and this seemed to completely end the focal...

**Comment by nebogeo** [comment]
Now the timer carries on when the screen is off - and it vibrates/makes a sound when the time is up. It's probably a good idea to turn off the screen as much as possible anyway in order to save battery life (it's the biggest drain).
