### ISSUE TITLE
obvious yes/no on toggle buttons

### ISSUE THREAD

**Issue by nebogeo** [fo-am/mongoose-2000#17]

**Comment by HarryHMarshall** [comment]
This is gratuitous and fantastic!! Would it be possible to tweak them to have three possible states? I.e. Yes/No/Unknown. Maybe a green paw and tick (as there is now), and red paw and a cross and a yellow(?) paw and a question mark...

**Comment by nebogeo** [comment]
will make three radio buttons for these options

**Comment by nebogeo** [comment]
(see https://github.com/nebogeo/mongoose-web/issues/18)
