### ISSUE TITLE
add unknown to toggles

### ISSUE THREAD

**Issue by nebogeo** [fo-am/mongoose-2000#18]
Just use a spinner?

**Comment by nebogeo** [comment]
Do we really want a spinner selector (like e.g. "Fighting over") or a tri-state toggle button that cycles between none -> yes -> no when clicked on?

**Comment by HarryHMarshall** [comment]
By a spinner selector do mean something that when you press, for example, "Winner?" a sub-window comes up asking you to select between Yes/No/Unknown? If so, no I think, if possible, some sort of tri-state button within the main window (so you can select and change it at any time whilst you are making the record) would be better.

**Comment by HarryHMarshall** [comment]
Sorry I didn't see you had flagged this as still to do. See my comment in the yes/no toggle button issue.
