### ISSUE TITLE
Sync screen seems to get stuck when uploading/downloading to/from the Pi

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#30]
When you press any of the push/pull/download/export buttons the first action seems to come up on the debug screen (e.g. "downloading <file path>") but then the screen seems to freeze after that. If you press the back button and then go back into the Sync screen a lot more actions then appear.

**Comment by nebogeo** [comment]
is this still the case with the new setup?

**Comment by HarryHMarshall** [comment]
Not sure - sorry things are a bit manic with Xmas and various visitors. 
Will try to have a look at this tomorrow afternoon or Thursday,

**Comment by nebogeo** [comment]
No worries, I'm changing all this tomorrow anyway - I'll do a release then too.

**Comment by nebogeo** [comment]
total rewrite of syncing system...
