### ISSUE TITLE
pause focal automatically when group events happen

### ISSUE THREAD

**Issue by JenniS** [fo-am/mongoose-2000#38]
can this happen? and stay paused until you manually un-pause it

**Comment by nebogeo** [comment]
just group events? - or pup focal events too?

**Comment by nebogeo** [comment]
done for group events

**Comment by HarryHMarshall** [comment]
Just group events as pup events are part of the focal.

On 9 Dec 2013, at 12:56, dave griffiths notifications@github.com wrote:

done for group events

—
Reply to this email directly or view it on
GitHubhttps://github.com/nebogeo/mongoose-web/issues/38#issuecomment-30129646
.
