### ISSUE TITLE
pack list in tag location not from database

### ISSUE THREAD

**Issue by JenniS** [fo-am/mongoose-2000#40]

**Comment by nebogeo** [comment]
do we still want tag location?

**Comment by JenniS** [comment]
Yes, I think so. Not entirely sure though - I'll check with the others and get back to you...

**Comment by HarryHMarshall** [comment]
This is equivalent to to using a handheld GPS to save a location right? 
If so, I would have thought it would be good to keep it/have it. Is it 
very difficult to implement?

**Comment by nebogeo** [comment]
no biggie to do this, so lets keep it in - I'll fix it.

**Comment by JenniS** [comment]
Great.

It'll need an option to tag a location without an assigned pack - is that ok?

**Comment by nebogeo** [comment]
yes, if the pack is unchecked it'll come back in the database as "NULL" - this goes for anything actually, we might need to make some things mandatory for sanity checking (like the pup individual in the pup focal)
