### ISSUE TITLE
add GPS

### ISSUE THREAD

**Issue by nebogeo** [fo-am/mongoose-2000#43]

**Comment by nebogeo** [comment]
added this - to conserve battery 3 minute updates + 5 metre resolution

**Comment by HarryHMarshall** [comment]
Is this to create a GPS track during the focal?

On 9 Dec 2013, at 21:12, dave griffiths notifications@github.com wrote:

added this - to conserve battery 3 minute updates + 5 metre resolution

—
Reply to this email directly or view it on
GitHubhttps://github.com/nebogeo/mongoose-web/issues/43#issuecomment-30173845
.

**Comment by nebogeo** [comment]
No this is for tagging all the records with GPS information. The positioning will be accurate to the last 3 minutes at most. You'll be able to build a track from the neighbour scans though.
