### ISSUE TITLE
Doing weights before group census

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#56]
When a group visit involves weighing mongooses, the weight data are the first thing that is recorded (it is often important to get them weighed quickly before they move off). This doubles as a group census since if an individual is weighed it is also present. If there are then any that are present but cannot be weighed these are then ticked off last.

Currently the app won't let you get to the weight data screen until you have recorded some individuals as present. Could this be swapped round so it asks you for weights first and then the group census? Then any individuals with a weight on the first screen would automatically be present but you could also select some extra individuals as present, i.e. individuals can have three states: weighed (and so present), present, not present.

For group visits involving no weights this first screen could be skipped past. Or, there could be two options in the initial observations screen: Group weights (current set of screens with weight screen first), Group composition (current set of screen but with the weight screen removed altogether). The guys know if they are going to weigh a pack before they find them so would know which option they wanted.

Let us know what is feasible/doable etc!

**Comment by nebogeo** [comment]
Yes this makes sense, doing it now...

**Comment by nebogeo** [comment]
Ok, done this but spent quite a while fighting ambiguous situations. It now works thusly:
- Weights is the first screen
- New toggle button in weight - "present but not weighed"
- It then goes straight to pregnant list (no more "present" selector)
  You can go back to weights/present and add new individuals.
