### ISSUE TITLE
Separate review changes by broader data type? E.g. group comp vs pup focal  

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#59]
Currently the records in the review changes are displayed in one list. The guys are likely to have at least four group compositions between each sync, and very likely more if they do some focals in a morning and/or don't sync their tablets for a day or so.

Would it be possible to split these records up into by data type and access these through a series of buttons? E.g. first select group comp or pup focal and then the pack or individual (and date), and then get the records associated with this. So if I wanted to find the group composition data I recorded from pack 11 on 17th July at 9:30am I'd hit group composition > pack 11 > 17/7/14 9:30. Perhaps not necessary to introduce that many layers in the record organisation, but you get the idea. Could even just have one layer of subsetting where the first screen was a lost of group compositions and focals and hitting these gave you the records associated with each.

**Comment by nebogeo** [comment]
Split into three levels - pup-focal/group-comp, then the depenant records (weights, etc) then the individual data attributes for editing...
