### ISSUE TITLE
add timestamped text notes

### ISSUE THREAD

**Issue by nebogeo** [fo-am/mongoose-2000#6]

**Comment by HarryHMarshall** [comment]
This is great. Could we consider 2 further tweaks to this? 

(1) At the moment "note" is in the group events panel on the screen. Could it be moved to be a stadalone button?
(2) Is it possible to have the cursor automatically in the text note text box once you hit "Note"? At the moment you need to tap the box to be able to type anything.

**Comment by nebogeo** [comment]
(1) - no where to put it, and group events are always accessible, so leaving this for now
(2) - done!
