### ISSUE TITLE
Change association and accuracy strength in pup and oestrus association from words (e.g. strong) to a number score (e.g. 1)?

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#60]
This works fine in the group composition screen but in the review changes screen these can be changed to anything (i.e. the input is not restricted). The guys have been using the number system for years and I think they are likely to revert to this out of habit when making any corrections, so introducing errors.

1 = strong, 2 = medium, 3 = weak

**Comment by nebogeo** [comment]
the selector is still strong/medium/weak but the database (viewable in review) now record as 3,2,1
