### ISSUE TITLE
Mongooses with unknown birth dates don't show up as options some mongoose selectors

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#62]
Selector menus affected: (Is that what they are called?!)
Pup focal scans
Pup Association (group comp)
Baby sitter (group comp)

**Comment by HarryHMarshall** [comment]
This is in the new "pack" I made - not sure if the same problem applies in other packs

**Comment by nebogeo** [comment]
When the birth date is unknown mongooses now appear in both adult and pup selections.
