### ISSUE TITLE
Syncing always seem to require the app to be restarted before it works

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#65]
Both times I tried syncing so far it seems to have got stuck when I have gone to it straight from recording data. Once you exit the app (keep pressing back) and then restart it it seems to work.

**Comment by nebogeo** [comment]
Lots of changes to this - haven't noticed it for a while.

**Comment by nebogeo** [comment]
Fixed a really slow part I recently introduced - seems to be much more responsive now...
