### ISSUE TITLE
pestering males

### ISSUE THREAD

**Issue by JenniS** [fo-am/mongoose-2000#66]
when a male is recorded as pestering but with strength none and accuracy none (which is often the case because we don't record strength and accuracy for pestering males) then his block remains light coloured - does this mean it is not recorded? 

Males are either guards OR pesterers - maybe it could be a choice between guarding and pestering rather than a yes/no for pestering? And then we only record the strength/accuracy data for guards

**Comment by nebogeo** [comment]
fixed!
