### ISSUE TITLE
More intuitive review changes interface

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#76]
Create more intuitive labels to describe the data in the review changes screen links to. For example the initial screen would show something like:

Date, Pack ID, Data type (Individual ID), Start time
e.g. 14/10/14, Pack 99, Pup Focal, AM001, 8:12AM
or    14/10/14, Pack 99, Group Composition, 7:23AM

Once you selected one of these you would then be shown a list of all the records under each of these groupings (perhaps with the grouong name written at the top of the screen?). So, something like:

For group compositions:
Data Type, Individual ID, Time
e.g. Weight, AF003, 7:56AM

and for pup focals:
Record time, Data type
e.g. 8:23AM, Nearest Neighbour

It would probably make sense for the buttons on each screen to be sorted by each of these fields - fist by the first field listed, and then the second etc etc.

**Comment by nebogeo** [comment]
I think this was done a while ago...
