### ISSUE TITLE
App does not seem to take account of the time zone?

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#82]
In collecting some dummy data the times recorded with each piece of data were all three hours behind the tablet time. I guess the app is just taking the GMT time and not accounting for time zone the tablet is in (GMT+3). This could be rectified by changing the base time the tablet is set at and telling it it is in the GMT+0 but would this mess up other functions (e.g. I think GPS works best if you have a unit set to the correct time and place?).

**Comment by nebogeo** [comment]
Aye aye - the app was doing everything in UTC, now obeys the local timezone...
