### ISSUE TITLE
Change binary data (1/0) in review changes to more intuitive yes/no?

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#83]
I'm sure the guys can easily work this out but it might  be easier to use if these data were displayed in the review changes using the more intuitive notation (such as yes/no) that is used in the main data recording interface.

**Comment by nebogeo** [comment]
So I think the review changes screens are really views of the raw underlying data, or at least are quite seperate to the input interface where the emphasis is on speed and clarity. It will be quite a big job if we start to make these screens into fully featured interfaces in their own right, I think they should be restricted to being just slightly above spreadsheet level really - open to feedback here though!

**Comment by HarryHMarshall** [comment]
The review changes seems to have been changed to yes/maybe/no now. I agree there's probably no need to make these fully functioning interfaces in their own right (or perhaps not until we run out of other things to add in!). 

Close this issue?
