### ISSUE TITLE
Need to be able to account for collar weights in the weights data

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#88]
I think this is something we forgot about. Some of the mongooses carry radio or GPS collars which all vary a bit in their weight depending in the type and size of the collar. This obviously needs to be accounted for in the weights data. 

Would it be possible to include a field somewhere for the collar wight to be entered? This could either be on the weighing screen of the group composition feature or in the individual information accessed through manage packs. The former would require the collar weight to be entered everytime so would be more labour intensive but should ensure it is regularly checked. The latter would require it only to be entered once when the collar was fitted but might then lead to errors if the guys forget to set it back to zero once the collar is removed. Perhaps a compromise might be to enter it in the manage packs screen but then have it automatically shown on the weights screen (if this is possible)?

Other mongoosers - what do you think?

**Comment by nebogeo** [comment]
added collar-weight to all mongooses
