### ISSUE TITLE
id-escort in mate-guarding review changes

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#89]
In the mate-guarding review changes the males ID is in a box marked as "id-escort". I guess the association data is all stored in the same fields since it all structurally the same (one focal, one partner ID and an accuracy and strength). Is it possible yo change how this is displayed in the review changes as it is a bit misleading.

**Comment by nebogeo** [comment]
I've changed this to "id-other" - as yes it needs to be the same structure for both, but it was more general than implied. Hope that's ok...
