### ISSUE TITLE
Focal group needed in group event review changes

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#90]
At the moment you can't change the Id of the group you were recording the data on in the group events review changes, only the group they were interacting with (in the case of group interactions). This sounds like something you shouldn't need to change but inevitably this is an error that will be made at some point!

**Comment by nebogeo** [comment]
Hah, much more serious - the current pack wasn't being recorded with group events! It is now. I guess you could have worked it out from the individuals involved. It will be possible to change the pack and mongoose id independantly now in review changes, but I think sanity checking that is probably a step too far...
