### ISSUE TITLE
App wouldn't automatically disconnect from other wireless network and connect to mongoose-web

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#91]
I think this is meant to happen? When I hit "Sync Me" the app kept trying to sync through the wi-fi network I was connected (called "mongoose") rather than connecting to "mongoose-web" (which it will do if the tablet isn't connected to any wireless network.

**Comment by nebogeo** [comment]
I've seen this sometimes before too - it seems to be a problem with the android OS, as I request a disconnection in the code, but it doesn't happen in some circumstances. Not much I can do about it, so more something to keep an eye on I'm afraid.
