### ISSUE TITLE
Display GPS output in interface

### ISSUE THREAD

**Issue by HarryHMarshall** [fo-am/mongoose-2000#94]
Show GPS coordinates being recorded with each record in the app interface so it's obvious when the tablet is not getting a GPS fix. (perhaps at the top of the screen - though doesn't necessarily need to be in a large font).

**Comment by HarryHMarshall** [comment]
I think this is still outstanding and is now high priority given the GPS functionality added in version 1.9. Just having the current lat, long and accuracy output at the top of the screen (it can be quite small) will allow the guys to see when the tablet is having trouble getting a GPS fix and so when to wait a minute before starting a focal or group composition.

**Comment by nebogeo** [comment]
I've now added a gps state on the main page, but it already flashes up the gps coords when it reads them, and there is the built in android gps indicator in the top bar too.

**Comment by HarryHMarshall** [comment]
This looks great and I think will be reassuring to the guys to see the 
"GPS Working" sign.

I think the guys were often missing the coordinates that flashed up. I 
suspect if we collected some data on their gaze direction when using the 
app we'd find that the majority of the time they were looking at the 
mongooses (or the bushes to check for marauding elephants/hippos etc).

By the android GPS indicator do you mean the little cross hairs with the 
flashing dots in the middle of it? This wasn't appearing very often 
before - I guess because it was idle quite a lot between requests from 
the app. However, it now seems to be on all the time - I guess because 
the app is essentially always asking for GPS update. IF this indicator 
is flashing does it necessarily mean the GPS has a fix of just that it 
is trying to obtain one?

**Comment by nebogeo** [comment]
Flashing indicates searching for satellites, steady on means it's working... and yup it'll be on more (not sure if all the time) as we are asking more frequently.

**Comment by HarryHMarshall** [comment]
Hmm...I'm getting a lot of flashing but also a lot of fixes. May be 
quite difficult get fixes as we have moved to the new building which is 
essentially encased in a big metal cage.
Do you know how good location fixes based on wifi alone are?

**Comment by nebogeo** [comment]
GPS in general doesn't work inside buildings (or in fact next to them). Fixes based on wifi are down to Google/Apple storing the location of every wifi access point in the world (sucking names using wifi scans from phones that know where they are). The third fallback is cellphone mast triangulation which is pretty inaccurate.
