### ISSUE TITLE
Start location and end location GPS

### ISSUE THREAD

**Issue by FayeThompson** [fo-am/mongoose-2000#96]
When a group composition or focal is started and finished we need the tablet to take a start and end location GPS point. Can this feature be added so the tablet automatically takes a start GPS on start of a group composition or focal (on selection in the main menu?), and an end GPS on end of a group composition or focal (on exiting?). If it is not possible for this to be done automatically, then can a button be added at the top of the start page of the group comp/focal to get the tablet to take a start GPS, and at the bottom of the end page to get the tablet to take an end GPS?

**Comment by nebogeo** [comment]
The GPS trails are done, I guess this fixes this...

**Comment by HarryHMarshall** [comment]
Yup - should do
